import Link from "next/link";
import { ArrowRight, ExternalLink } from "lucide-react";

const programs=[
 {title:"Kazy Creative",image:"/assets/del3.jpg",tag:"Employment pathways",text:"The employment component responds to two different realities. Young people who already have formal training receive value-addition support to strengthen their skills and readiness for work. Those without formal training first move through Kazy Creative learning components before progressing to job placement support. Open Spaces support learning and mentorship, Idea Spaces help participants test and improve concepts, and Work Spaces provide the practical environment needed to build, make and deliver."},
 {title:"Mental Health & Wellness Support",image:"/assets/afya3.jpg",tag:"Healthy minds, sustainable progress",text:"WorldWaysOne supports the mental health and wellness of young people through safe, practical and non-judgmental spaces. Open Spaces host conversations and wellness activities; Idea Spaces encourage creative expression, reflection and personal growth; and Work Spaces turn learning into healthy routines and meaningful action. Programs are designed to build confidence, resilience, self-awareness and the ability to seek appropriate support."},
 {title:"Entrepreneurship & Youth Training",image:"/assets/slide-3.jpg",tag:"From idea to viable enterprise",text:"Interactive training, workshops and mentorship help young people develop business ideas, understand customers, refine value propositions and build basic financial and operating skills. Idea Spaces support innovation and product development, while Work Spaces provide access to tools and environments for practical learning. The aim is not simply to teach enterprise vocabulary, but to help participants test ideas and create sustainable opportunities for themselves and their communities."},
 {title:"Socio-Emotional Skills Development",image:"/assets/gallery--1.jpg",tag:"Skills for life and work",text:"Kazy Creative nurtures communication, empathy, teamwork, self-awareness, emotional intelligence and problem-solving. Group activities, mentorship and wellness workshops offer room to practise these abilities safely. Reflection and collaborative projects help young people understand themselves and others, while real-world work tasks make the learning practical for personal relationships, leadership and professional life."},
 {title:"Digital Skills & Coding Bootcamps",image:"/assets/youth1.jpg",tag:"Readiness for a digital future",text:"Hands-on digital literacy and coding programs introduce young people to practical tools, programming concepts, collaborative problem-solving, app and web development, and responsible online participation. Interactive workshops create a strong foundation; innovation sessions help participants design their own digital projects; and equipped work sessions provide time to practise, build and receive support."},
];
export const metadata={title:"Youth empowerment"};
export default function Youth(){return <main><section className="inner-hero youth-hero"><img src="/assets/slide-3.jpg" alt="Young people taking part in a WorldWaysOne program"/><div className="hero-shade"/><div><p className="kicker light">YOUTH EMPOWERMENT</p><h1>Potential becomes progress with the right support.</h1><p>WorldWaysOne recognizes that every person has a unique talent and the potential to accomplish it. Our role is to provide the skills, mentorship, spaces and access that help young people actualize that potential.</p></div></section>
 <section className="section-pad youth-intro"><p className="kicker">HOW WE WORK</p><div><h2>Learning linked to real opportunity.</h2><p>Programs are designed around three connected environments: <strong>Open Spaces</strong> for learning, forums and mentorship; <strong>Idea Spaces</strong> for creativity, problem-solving and enterprise development; and <strong>Work Spaces</strong> where participants use tools, practise skills and turn ideas into practical outputs.</p></div></section>
 <section className="youth-programs section-pad">{programs.map((p,i)=><article key={p.title} className={i%2?"reverse":""}><div className="program-photo"><img src={p.image} alt={p.title}/><span>0{i+1}</span></div><div><p className="kicker">{p.tag}</p><h2>{p.title}</h2><p>{p.text}</p><Link className="text-link" href="/contact">Discuss this program <ArrowRight/></Link></div></article>)}</section>
 <section className="nyota-section section-pad"><div><p className="kicker light">NATIONAL OPPORTUNITY</p><h2>Understanding the NYOTA Project</h2><p>The National Youth Opportunities Towards Advancement (NYOTA) Project is a five-year Government of Kenya initiative intended to improve youth employability, earnings and savings. Its official program areas include employment and apprenticeships, enterprise support, recognition of prior learning, socio-emotional skills and stronger youth employment systems.</p><p>WorldWaysOne helps young people interpret opportunities, strengthen readiness and build the practical skills needed to participate. Eligibility, application windows and awards are controlled by the official NYOTA Project—not by WorldWaysOne—and applicants should always confirm current requirements on the government portal.</p><a className="button light-button" href="https://nyotaproject.go.ke/" target="_blank" rel="noreferrer">Visit the official NYOTA portal <ExternalLink/></a></div><img src="/assets/Bomet.jpg" alt="Young professionals participating in an international learning program"/></section>
 <section className="section-pad youth-cta"><div><p className="kicker">FOR YOUNG PEOPLE, SCHOOLS & PARTNERS</p><h2>Build a program around the outcomes that matter.</h2></div><Link href="/contact" className="button dark-button">Talk to our program team <ArrowRight/></Link></section>
</main>}
