import { Eye, Gem, Handshake } from "lucide-react";
export const metadata={title:"About us"};
export default function About(){return <main>
  <section className="inner-hero about-hero"><img src="/assets/about-1i.jpg" alt="WorldWaysOne team and community"/><div className="hero-shade"/><div><p className="kicker light">OUR STORY</p><h1>Connection is where possibility begins.</h1><p>WorldWaysOne brings people, institutions, ideas and places together to create meaningful progress.</p></div></section>
  <section className="section-pad story"><p className="kicker">SINCE 2015</p><div><h2>A Nairobi organization with a worldwide outlook.</h2><p>WorldWaysOne Ventures Limited connects people with opportunities around the world. We coordinate travel and delegations, facilitate conferences and professional visits, deliver corporate training and consultation, provide legal support through our professional affiliation, and design youth empowerment programs that turn potential into practical opportunity.</p><p>Our platform connects people, technology and innovation with leaders, decision-makers, companies and investors—always with dignity, transparency and respect.</p></div></section>
  <section className="values section-pad"><div className="section-title"><div><p className="kicker">OUR VALUES</p><h2>Standards that shape every engagement.</h2></div></div><div className="pillar-grid"><article><Gem/><h3>Professionalism</h3><p>Every job is done efficiently and professionally with the client in mind.</p></article><article><Eye/><h3>Integrity</h3><p>We insist on maintaining integrity in everything we do.</p></article><article><Handshake/><h3>Accountability</h3><p>In order to do more with less for more, accountability is our pride.</p></article></div></section>
  <section className="team section-pad"><div className="section-title"><div><p className="kicker">FOUNDERS & LEADERSHIP</p><h2>People behind the purpose.</h2></div></div><div className="team-grid founder-grid"><article><img src="/assets/keniz.jpg" alt="Mr Keniz Agira"/><div><h3>Mr Keniz Agira</h3><p className="role">Advocate of the High Court of Kenya</p><p>We aim at challenging the status quo and finding new ways to grow our company and each other while being present, connecting with transparency, dignity and respect.</p></div></article><article><img src="/assets/john.jpg" alt="Mr John Ougo"/><div><h3>Mr John Ougo</h3><p className="role">Public Health Practitioner</p><p>We continue to serve customer needs through safe, practical and convenient methods, adapting our work to the people and communities we support.</p></div></article><article><img src="/assets/suzan.jpg" alt="Mrs Susan Jason"/><div><h3>Mrs Susan Jason</h3><p className="role">Business Development Lead</p><p>We pride ourselves on professionalism, integrity and accountability in every business engagement. These values have supported the organization’s growth over the years.</p></div></article></div></section>
  <section className="partners section-pad"><p className="kicker">OUR NETWORK</p><h2>Partners in possibility.</h2><div className="partner-marquee"><div className="partner-track">{[...Array(2)].flatMap((_,round)=>["partner 1.jpg","partner2.jpg","partner3.png","partner4.jpg","partner7.jpg","partner8.jpg","partner9.jpg","partner10.jpg","partner11.jpg","partner12.jpg","partner13.jpg"].map(x=><div key={`${round}-${x}`}><img src={`/assets/${x}`} alt="WorldWaysOne partner organization"/></div>))}</div></div></section>
</main>}
