import Link from "next/link";
import { ArrowRight, ArrowUpRight, Globe2, ShieldCheck, Sparkles, Users } from "lucide-react";
import { itineraries } from "@/lib/site-data";

const pillars=[{icon:Globe2,title:"Travel with purpose",text:"Curated journeys shaped around learning, connection and memorable discovery."},{icon:Users,title:"People before plans",text:"Every itinerary begins by understanding who you are and why you are travelling."},{icon:ShieldCheck,title:"Confidence throughout",text:"Experienced coordination, clear communication and dependable on-ground support."}];
export default function Home(){return <main>
  <section className="home-hero"><img src="/assets/Banner-Kenya.webp" alt="Safari landscape in Kenya"/><div className="hero-shade"/><div className="hero-content"><p className="kicker light">WORLDWAYSOne VENTURES · NAIROBI</p><h1>Journeys that open<br/>the world.</h1><p>Tailor-made travel, international delegations and programs that connect people to places, knowledge and opportunity.</p><div className="hero-actions"><Link href="/itineraries" className="button light-button">Explore itineraries <ArrowRight/></Link><Link href="/contact" className="text-link light">Plan with us <ArrowUpRight/></Link></div></div><div className="hero-note"><span>01</span><p>Safari, culture and coast<br/>across East Africa</p></div></section>
  <section className="intro section-pad"><div><p className="kicker">WORLDWIDE, BY DESIGN</p><h2>Travel is more meaningful when every detail has a reason.</h2></div><div><p className="large-copy">Since 2015, WorldWaysOne has connected travellers, institutions and young people with experiences that broaden perspective and create lasting value.</p><Link className="text-link" href="/about">Our story <ArrowUpRight/></Link></div></section>
  <section className="experience-band"><div className="experience-image"><img src="/assets/del3.jpg" alt="WorldWaysOne academic delegation on an international study tour"/></div><div className="experience-copy"><p className="kicker light">THE WORLD, YOUR WAY</p><h2>From classroom to continent.</h2><p>Academic tours, private journeys, safaris, pilgrimages and professional delegations—carefully coordinated from departure to return.</p><div className="experience-links"><Link href="/services/academic-tours">Academic travel <ArrowUpRight/></Link><Link href="/services/safari-tours">East Africa safaris <ArrowUpRight/></Link><Link href="/services/delegations">Delegations <ArrowUpRight/></Link></div></div></section>
  <section className="section-pad journeys"><div className="section-title"><div><p className="kicker">SIGNATURE JOURNEYS</p><h2>Start with inspiration.<br/>Make it entirely yours.</h2></div><Link className="text-link" href="/itineraries">View every itinerary <ArrowRight/></Link></div><div className="journey-grid">{itineraries.slice(0,3).map((item,i)=><Link className="journey-card" href="/itineraries" key={item.title}><div className="journey-image"><img src={item.image} alt=""/><span>0{i+1}</span></div><div><p>{item.region} · {item.duration}</p><h3>{item.title}</h3></div></Link>)}</div></section>
  <section className="program-feature"><div><p className="kicker">BEYOND TRAVEL</p><h2>Opportunity should travel further than we do.</h2><p>Our youth programs turn access, mentorship and practical learning into pathways for entrepreneurship, digital skills, wellbeing and sustainable work.</p><Link href="/services/youth-empowerment" className="button dark-button">Explore youth programs <ArrowRight/></Link></div><div className="collage"><img src="/assets/youth1.jpg" alt="WorldWaysOne youth program participants"/><img src="/assets/gallery--1.jpg" alt="Learning and mentorship session"/></div></section>
  <section className="section-pad pillars"><div className="section-title"><div><p className="kicker">WHY WORLDWAYSONE</p><h2>Considered from every angle.</h2></div></div><div className="pillar-grid">{pillars.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="legal-feature"><img src="/assets/legal.jpeg" alt="Professional legal consultation"/><div><p className="kicker light">A TRUSTED AFFILIATION</p><h2>Keniz Agira & Company Advocates</h2><p>WorldWaysOne clients can access practical legal support spanning corporate and commercial law, ICT law, contracts, advisory and representation.</p><Link href="/services/legal-services" className="text-link light">Legal services <ArrowUpRight/></Link></div></section>
  <section className="section-pad proof"><div><p className="kicker">CONNECTED EXPERIENCE</p><h2>Built through real journeys.</h2></div><div className="proof-grid"><p><strong>2015</strong><span>Connecting people with opportunities since</span></p><p><strong>3</strong><span>Continents represented in current programs</span></p><p><strong>7/7</strong><span>Customer support throughout the week</span></p><p><Sparkles/><span>Travel, learning and opportunity in one network</span></p></div></section>
</main>}
