import Link from "next/link";
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Globe2, HeartHandshake, Scale, Sparkles, Users } from "lucide-react";
import { HeroSlider } from "@/components/hero-slider";

const pillars=[{icon:Users,title:"Youth empowerment",text:"Skills, mentorship, enterprise support and spaces where young people can learn, create and work.",href:"/youth"},{icon:BriefcaseBusiness,title:"Consultation",text:"Research, cybersecurity, surveys, publications, training and practical organizational advisory.",href:"/services/consultation"},{icon:Globe2,title:"Delegations",text:"Conferences, exchanges and professional visits coordinated end to end, locally and internationally.",href:"/services/delegations"},{icon:HeartHandshake,title:"Travel & tours",text:"Educational, private, safari, cruise and faith journeys designed around a clear purpose.",href:"/services/academic-tours"},{icon:Scale,title:"Legal services",text:"Corporate, commercial, ICT and contract support through Keniz Agira & Company Advocates.",href:"/services/legal-services"}];
export default function Home(){return <main><HeroSlider/>
  <section className="intro section-pad"><div><p className="kicker">WHO WE ARE</p><h2>One organization. Several ways to move people forward.</h2></div><div><p className="large-copy">WorldWaysOne Ventures Limited connects people, technology, innovation and institutions with opportunities around the world. Our work spans youth development, consulting, delegations, legal support, wellbeing and travel.</p><Link className="text-link" href="/about">Read our story <ArrowUpRight/></Link></div></section>
  <section className="work-grid section-pad"><div className="section-title"><div><p className="kicker">OUR WORK</p><h2>Built around people,<br/>purpose and progress.</h2></div></div><div className="work-cards">{pillars.map(({icon:Icon,title,text,href},i)=><Link href={href} key={title} className="work-card"><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p><ArrowUpRight className="corner-arrow"/></Link>)}</div></section>
  <section className="experience-band"><div className="experience-image"><img src="/assets/del3.jpg" alt="WorldWaysOne delegates during an international learning visit"/></div><div className="experience-copy"><p className="kicker light">DELEGATIONS & EXCHANGE</p><h2>Global exposure with a clear purpose.</h2><p>We coordinate conferences, academic and cultural exchanges, historical visits, professional missions and institutional tours. Registration, travel logistics, documentation, protocol and on-ground facilitation are handled as one connected program.</p><div className="experience-links"><Link href="/services/delegations">Delegation management <ArrowUpRight/></Link><Link href="/services/academic-tours">Academic study tours <ArrowUpRight/></Link><Link href="/stories">See recent activities <ArrowUpRight/></Link></div></div></section>
  <section className="program-feature"><div><p className="kicker">YOUTH EMPOWERMENT</p><h2>Talent grows when opportunity is practical.</h2><p>We design programs that equip young people with employability, entrepreneurship, digital, socio-emotional and wellbeing skills. Kazy Creative provides pathways from learning to work, while our training and mentorship spaces help ideas become viable livelihoods.</p><Link href="/youth" className="button dark-button">Explore every program <ArrowRight/></Link></div><div className="collage"><img src="/assets/youth1.jpg" alt="Digital skills and coding training"/><img src="/assets/gallery--1.jpg" alt="WorldWaysOne youth program participants"/></div></section>
  <section className="legal-feature"><img src="/assets/legal.jpeg" alt="Professional legal consultation"/><div><p className="kicker light">PROFESSIONAL AFFILIATION</p><h2>Keniz Agira & Company Advocates</h2><p>WorldWaysOne clients can access practical legal guidance across corporate and commercial law, ICT law, contracts, advisory and representation.</p><Link href="/services/legal-services" className="text-link light">Explore legal services <ArrowUpRight/></Link></div></section>
  <section className="section-pad proof"><div><p className="kicker">CONNECTED EXPERIENCE</p><h2>Grounded locally.<br/>Connected globally.</h2></div><div className="proof-grid"><p><strong>2015</strong><span>Connecting people with opportunities since</span></p><p><strong>6</strong><span>Integrated areas of service and impact</span></p><p><strong>7/7</strong><span>Customer support throughout the week</span></p><p><Sparkles/><span>Professional work shaped around real people and needs</span></p></div></section>
</main>}
