import Link from "next/link";
import { ArrowRight, CalendarDays } from "lucide-react";
export const metadata={title:"Recent uploads & successful events"};
const posts=[
 {title:"Cruise tours: comfort, discovery and new horizons",date:"Oct 6, 2025",image:"/assets/cruise-pool.webp",text:"Sail away on a memorable voyage that blends adventure, comfort and discovery. WorldWaysOne cruise tours combine time to unwind with thoughtfully planned port experiences, local culture, cuisine and scenery.",href:"/services/cruise-tours"},
 {title:"Academic and study tours",date:"Oct 6, 2025",image:"/assets/gallery--1.jpg",text:"Designed for schools, universities and professional institutions, these programs extend classroom learning into universities, research centres, museums, innovation spaces and global cultural experiences.",href:"/services/academic-tours"},
 {title:"Professional travel and historical tours",date:"Oct 6, 2025",image:"/assets/jerusalem.jpg",text:"Specialized journeys for practitioners, researchers and industry groups provide access to global institutions, professional exchange and the historical places that continue to shape contemporary society.",href:"/services/delegations"},
 {title:"Corporate and commercial law",date:"Oct 6, 2025",image:"/assets/legal.jpeg",text:"Through Keniz Agira & Company Advocates, clients receive support with company formation, governance, regulatory compliance, commercial negotiation, agreements and strategic risk management.",href:"/services/legal-services"},
 {title:"Legal advisory and representation",date:"Oct 6, 2025",image:"/assets/law.png",text:"Personalized legal guidance and professional representation across litigation, dispute resolution, compliance and rights protection—explained clearly and handled with care.",href:"/services/legal-services"},
 {title:"Technology conferences and professional exchange",date:"WorldWaysOne activities",image:"/assets/tech.jpg",text:"WorldWaysOne delegations participate in international conferences and learning exchanges that connect professionals to new knowledge, institutions and networks.",href:"/services/delegations"},
 {title:"Cultural exchange and institutional visits",date:"WorldWaysOne activities",image:"/assets/del3.jpg",text:"Academic and cultural exchanges create meaningful contact between learners, educators and institutions while building global awareness and professional confidence.",href:"/stories"},
 {title:"Youth entrepreneurship and practical training",date:"WorldWaysOne programs",image:"/assets/slide-3.jpg",text:"Workshops, mentorship and practical spaces help young people refine ideas, learn essential enterprise skills and move towards sustainable work.",href:"/youth"}
];
export default function RecentUploads(){return <main><section className="page-heading uploads-heading"><p className="kicker">RECENT UPLOADS</p><h1>Our successful events,<br/><em>programs and journeys.</em></h1><p>News and visual stories from WorldWaysOne’s work in travel, professional exchange, legal services, youth development and international collaboration.</p></section><section className="uploads-grid section-pad">{posts.map((post,i)=><article key={post.title} className={i===0?"featured":""}><Link href={post.href} className="upload-image"><img src={post.image} alt={post.title}/><span>{String(i+1).padStart(2,"0")}</span></Link><div className="upload-copy"><p className="upload-date"><CalendarDays/> {post.date}</p><h2>{post.title}</h2><p>{post.text}</p><Link className="text-link" href={post.href}>Read the full story <ArrowRight/></Link></div></article>)}</section><section className="uploads-cta section-pad"><div><p className="kicker light">WORK WITH US</p><h2>Planning an event, program or journey?</h2></div><Link href="/contact" className="button light-button">Start a conversation <ArrowRight/></Link></section></main>}
