export type Service = {
  slug: string; eyebrow: string; title: string; summary: string; intro: string;
  image: string; features: string[]; details: string[]; cta?: string;
};

export const services: Service[] = [
  { slug:"academic-tours", eyebrow:"Educational travel", title:"Academic & study tours", summary:"10–14 day global learning journeys that bridge classroom theory with universities, research centres, museums and industry.", intro:"Designed for schools, universities and professional institutions, our study tours combine academic engagement, cultural immersion and carefully managed travel from Nairobi.", image:"/assets/del2.jpg", features:["University and research-centre visits","Industry and innovation-hub access","Academic workshops and faculty exchange","Cultural immersion and guided city experiences"], details:["Destinations across Europe, Asia and North America","Flights, accommodation, learning visits and meals can be included","Visa guidance and documentation support","Student presentations and reflective project work"] },
  { slug:"family-tours", eyebrow:"Private journeys", title:"Private & family tours", summary:"Thoughtful, private escapes balancing discovery, culture, adventure and time to simply be together.", intro:"From East African safaris to Indian Ocean islands and international city breaks, every journey is arranged around your pace, interests and preferred level of comfort.", image:"/assets/kenya-family.jpg", features:["Private game drives and luxury lodges","Cultural experiences and city tours","Beach, island and spa retreats","Family-friendly guides and flexible pacing"], details:["Kenya, Tanzania, Morocco, Egypt and South Africa","Zanzibar, Seychelles, Mauritius and the Maldives","Dubai and Abu Dhabi city and desert experiences","Romantic and milestone celebration journeys"] },
  { slug:"cruise-tours", eyebrow:"Ocean journeys", title:"Cruise tours", summary:"Memorable voyages pairing the ease of a cruise with well-planned discoveries on shore.", intro:"We support cruise selection, pre- and post-cruise stays, flights, transfers, documentation and curated shore experiences for couples, families and groups.", image:"/assets/cruise-pool.webp", features:["Cruise and cabin selection","Flights, transfers and accommodation","Curated port excursions","Group and family coordination"], details:["End-to-end travel support","Flexible extensions before or after sailing","Documentation and insurance guidance","Personalised options for special occasions"] },
  { slug:"nairobi-excursions", eyebrow:"Local travel", title:"Nairobi excursions", summary:"See Kenya’s capital through wildlife, culture, history and the people shaping its future.", intro:"Flexible full-day and half-day experiences connect guests to Nairobi National Park, conservation centres, museums, markets and cultural spaces.", image:"/assets/nairobi-banner.jpg", features:["Nairobi National Park","Giraffe Centre and conservation visits","Bomas of Kenya","Museums, markets and local food"], details:["Private transport and professional guides","Airport or hotel pick-up options","Custom itineraries for schools and groups","Family-friendly scheduling"] },
  { slug:"mombasa-excursions", eyebrow:"Coast experiences", title:"Mombasa excursions", summary:"Swahili heritage, Indian Ocean beaches and coastal experiences shaped around you.", intro:"Discover Mombasa Old Town, Fort Jesus, coastal cuisine, marine experiences and the beaches of Diani through well-paced private outings.", image:"/assets/mombasa-diani.jpg", features:["Fort Jesus and Old Town","Diani and north-coast beaches","Swahili culture and cuisine","Marine and dhow experiences"], details:["Private transfers and guides","Family and group options","Beach-stay extensions","Custom cultural itineraries"] },
  { slug:"safari-tours", eyebrow:"East Africa", title:"Safari tours", summary:"Distinctive wildlife journeys through Kenya’s renowned parks and conservancies.", intro:"Our safari planning combines knowledgeable guides, carefully selected camps, considered pacing and the landscapes that make East Africa unforgettable.", image:"/assets/safari1.jpg", features:["Maasai Mara and Amboseli","Samburu and Lewa Conservancy","Private and group game drives","Lodges, tented camps and conservancies"], details:["Road and fly-in safari options","Family and photographic safaris","Cultural and conservation encounters","Beach-and-bush combinations"] },
  { slug:"custom-excursions", eyebrow:"Made for you", title:"Custom tours & excursions", summary:"A travel plan built from the ground up around your group, purpose, timing and budget.", intro:"We create tailored programs for organizations, corporates, schools, families, faith communities and special-interest groups.", image:"/assets/Banner-Kenya.webp", features:["Purpose-built itineraries","Accommodation and transport","On-ground facilitation","Group logistics and documentation"], details:["Local and international destinations","Special-interest and professional visits","Celebrations and private groups","Flexible duration and service levels"] },
  { slug:"europe-pilgrimage", eyebrow:"Faith journeys", title:"Europe pilgrimage", summary:"Spiritually meaningful travel across Europe’s sacred places, cultural landmarks and living communities.", intro:"Our pilgrimage programs combine thoughtful spiritual direction, dependable logistics and time to encounter the history and beauty of each destination.", image:"/assets/Fatima banner.webp", features:["Rome and Vatican City","Assisi and sacred Italy","Fatima and European shrines","Guided worship and reflection"], details:["Flights and group transfers","Accommodation and selected meals","Pilgrimage guides and local coordination","Visa and documentation support"] },
  { slug:"holy-land-pilgrimage", eyebrow:"Faith journeys", title:"Holy Land pilgrimage", summary:"Walk through places central to faith, history and centuries of pilgrimage.", intro:"We coordinate carefully paced Holy Land programs for churches, ministries, families and faith groups, with guided visits and complete group support.", image:"/assets/jerusalem.jpg", features:["Jerusalem and Bethlehem","Historic and biblical sites","Faith-centred group programming","Professional local guides"], details:["Group flight coordination","Accommodation and ground transport","Documentation guidance","Custom programs for church communities"] },
  { slug:"youth-empowerment", eyebrow:"Opportunity & growth", title:"Youth training & empowerment", summary:"Programs that equip young people with skills, mentorship and pathways to sustainable opportunity.", intro:"WorldWaysOne believes every young person carries distinct potential. Our programs provide the external trigger—support, learning and access—that helps that potential become progress.", image:"/assets/youth1.jpg", features:["Kazy Creative employment pathways","Mental health and wellness support","Entrepreneurship and youth training","Digital skills and coding bootcamps"], details:["Socio-emotional skills development","Mentorship and leadership forums","Career development and innovation challenges","Community-driven projects"] },
  { slug:"consultation", eyebrow:"Research & advisory", title:"Consultation services", summary:"Evidence-led guidance for organizations navigating technology, markets, advocacy and growth.", intro:"We create practical knowledge, research and tailored solutions that help institutions understand their context and act with confidence.", image:"/assets/con1.jpg", features:["Cybersecurity advisory","Publications and knowledge products","Market and community surveys","Strategic advocacy"], details:["Research-driven product solutions","Youth development insights","Capacity-building workshops","Reports, articles and thought leadership"] },
  { slug:"delegations", eyebrow:"Global connection", title:"International delegations", summary:"End-to-end coordination for conferences, summits, exchanges, study tours and professional visits.", intro:"Our team manages travel logistics, documentation, protocol, registration, itineraries and on-ground facilitation so every delegation can focus on its purpose.", image:"/assets/conf.jpg", features:["International conferences and forums","Academic and cultural exchange","Professional and historical visits","Custom delegation management"], details:["Registration and protocol support","Travel and documentation coordination","Institutional and industry visits","On-ground facilitation"] },
  { slug:"legal-services", eyebrow:"Professional services", title:"Legal services", summary:"Reliable, practical legal guidance for individuals, businesses and organizations.", intro:"Through our affiliation with Keniz Agira & Company Advocates, clients access professional legal insight grounded in clarity, responsiveness and a strong understanding of evolving legal environments.", image:"/assets/legal.jpeg", features:["Legal advisory and representation","ICT law","Corporate and commercial law","Contract drafting and review"], details:["Legal literacy and community outreach","Business formation and governance support","Practical review of legal risk","Client-centred representation"] },
  { slug:"health-wellness", eyebrow:"Wellbeing", title:"Health & wellness", summary:"Community-minded programs supporting informed, resilient and healthy lives.", intro:"Our wellbeing work connects people to practical knowledge, supportive spaces and initiatives that recognise the relationship between health, opportunity and human development.", image:"/assets/afya3.jpg", features:["Mental health awareness","Wellness support","Community education","Youth-centred wellbeing"], details:["Supportive program design","Partner-led initiatives","Learning and advocacy","Integrated youth-development approach"] },
];

export const itineraries = [
  { title:"Academic & Educational Tours", duration:"Program based", region:"Worldwide", image:"/assets/del3.jpg", href:"https://traveljoy.com/client/rYAz7vYWYY54jygWjQnSXFBB/view_proposal/Q7MBb3Rt5SWy7Ji74MvEXQWA", summary:"University, research-centre, museum, industry and cultural visits for schools, institutions and professional groups." },
  { title:"Private & Family Tours", duration:"Tailor-made", region:"Africa & worldwide", image:"/assets/kenya-family.jpg", href:"https://traveljoy.com/client/rYAz7vYWYY54jygWjQnSXFBB/view_proposal/Q7MBb3Rt5SWy7Ji74MvEXQWA", summary:"Private journeys combining wildlife, culture, beach stays and experiences paced for your family or group." },
  { title:"Kenya Safari Tours", duration:"Tailor-made", region:"Kenya", image:"/assets/ambos.webp", href:"https://traveljoy.com/client/rYAz7vYWYY54jygWjQnSXFBB/view_proposal/Q7MBb3Rt5SWy7Ji74MvEXQWAtps://worldwaysone.co.ke/safari-tours.php", summary:"Wildlife journeys through parks and conservancies, with road or fly-in options and considered accommodation." },
  { title:"Nairobi Excursions", duration:"Half or full day", region:"Nairobi", image:"/assets/Nairobi-Giraffe.webp", href:"https://traveljoy.com/client/rYAz7vYWYY54jygWjQnSXFBB/view_proposal/Q7MBb3Rt5SWy7Ji74MvEXQWA", summary:"City, culture and conservation experiences including the national park, museums, markets and heritage sites." },
  { title:"Mombasa Excursions", duration:"Flexible", region:"Kenyan coast", image:"/assets/mombasa-diani.jpg", href:"https://worldwaysone.co.ke/mombasa-tours.php", summary:"Old Town, Fort Jesus, Swahili culture, marine excursions and Indian Ocean beach experiences." },
  { title:"Europe Pilgrimage", duration:"Program based", region:"Europe", image:"/assets/Fatima banner.webp", href:"https://traveljoy.com/client/rYAz7vYWYY54jygWjQnSXFBB/view_proposal/Q7MBb3Rt5SWy7Ji74MvEXQWA", summary:"Faith-centred travel across Rome, Vatican City, Assisi, Fatima and other sacred and cultural destinations." },
  { title:"Holy Land Pilgrimage", duration:"Program based", region:"Holy Land", image:"/assets/jerusalem.jpg", href:"https://traveljoy.com/client/rYAz7vYWYY54jygWjQnSXFBB/view_proposal/Q7MBb3Rt5SWy7Ji74MvEXQWAhttps://worldwaysone.co.ke/holiday-pilgrimage.php", summary:"Guided visits to places of faith and history, arranged for churches, ministries, families and groups." },
  { title:"Cruise Tours", duration:"Sailing based", region:"International", image:"/assets/cruise-pool.webp", href:"https://traveljoy.com/client/rYAz7vYWYY54jygWjQnSXFBB/view_proposal/Q7MBb3Rt5SWy7Ji74MvEXQWA", summary:"Cruise selection, flights, transfers, pre- and post-stays, documentation and curated shore excursions." },
];

export const navTravel = services.slice(0, 8);
export const navPrograms = services.slice(8);
export const serviceBySlug = Object.fromEntries(services.map((s) => [s.slug, s]));
