import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { serviceBySlug, services } from "@/lib/site-data";
import { EmailForm } from "@/components/email-form";

const travelSlugs=new Set(["academic-tours","family-tours","cruise-tours","nairobi-excursions","mombasa-excursions","safari-tours","custom-excursions","europe-pilgrimage","holy-land-pilgrimage"]);
const official:Record<string,string>={"academic-tours":"academic-tours.php","family-tours":"family-tours.php","cruise-tours":"cruise-tours.php","nairobi-excursions":"nairobi-tours.php","mombasa-excursions":"mombasa-tours.php","safari-tours":"safari-tours.php","custom-excursions":"other-destinations.php","europe-pilgrimage":"europe-tours.php","holy-land-pilgrimage":"holiday-pilgrimage.php"};

export function generateStaticParams(){return services.map(({slug})=>({slug}))}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=serviceBySlug[slug];if(!service)notFound();const isTravel=travelSlugs.has(slug);return <main>
  <section className="inner-hero"><img src={service.image} alt=""/><div className="hero-shade"/><div><p className="kicker light">{service.eyebrow}</p><h1>{service.title}</h1><p>{service.summary}</p></div></section>
  <section className="section-pad service-intro"><p className="kicker">THE EXPERIENCE</p><div><h2>{service.intro}</h2><Link href="/contact" className="button dark-button">Enquire now <ArrowRight/></Link></div></section>
  <section className="service-detail"><div><p className="kicker light">WHAT TO EXPECT</p><h2>Designed around your purpose.</h2></div><div className="feature-list">{service.features.map(x=><p key={x}><Check/> {x}</p>)}</div></section>
  <section className="section-pad detail-grid"><div><p className="kicker">THOUGHTFUL DETAILS</p><h2>From first idea to the final day.</h2></div><ul>{service.details.map(x=><li key={x}>{x}</li>)}</ul></section>
  {isTravel&&<><section className="travel-facts section-pad"><div className="rate-banner"><div><p className="kicker light">CURRENT RATES</p><h2>Quoted for your exact journey.</h2></div><p>Airfares, exchange rates, accommodation and availability change. We do not publish a stale fixed price. Send your dates and group size to receive the current written rate and payment schedule.</p></div><div className="fact-grid"><article><h3>Typically included</h3><ul><li>Return transport or flights where stated</li><li>Confirmed accommodation category</li><li>Selected meals in the final proposal</li><li>Entrance fees and guided visits</li><li>Ground coordination and transfers</li></ul></article><article><h3>Usually excluded</h3><ul><li>Visa fees unless expressly stated</li><li>Travel insurance</li><li>Personal expenses, tips and optional activities</li><li>Meals not listed in the proposal</li><li>Changes caused by personal schedule adjustments</li></ul></article><article><h3>Documents required</h3><ul><li>Passport valid for at least six months</li><li>Passport-size photographs where required</li><li>Visa forms and supporting documents</li><li>Copy of national ID and travel insurance</li><li>Minor consent or school documents where applicable</li></ul></article><article><h3>Terms & conditions</h3><ul><li>Registration fees are non-refundable unless stated otherwise</li><li>Final balance is generally due 30 days before departure</li><li>Supplier, airline and hotel conditions apply</li><li>Programs may change for safety or local conditions</li><li>Only the final written quotation confirms price and inclusions</li></ul></article></div></section><section className="tour-enquiry section-pad"><div><p className="kicker">PLAN THIS JOURNEY</p><h2>Tell us who is travelling.</h2><p>Share the adults, children, dates and destination. Our team will reply with the current rate, exact inclusions, documentation checklist and payment terms.</p><a className="text-link" href={`https://worldwaysone.co.ke/${official[slug]}`} target="_blank" rel="noreferrer">View the original WorldWaysOne details</a></div><EmailForm tour={service.title}/></section></>}
</main>}
